[book]
title = "Learn Rust with Tests"
authors = ["you"]
language = "en"
src = "src"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/TODO/learn-rust-with-tests"
edit-url-template = "https://github.com/TODO/learn-rust-with-tests/edit/main/{path}"

[output.html.playground]
editable = true
copy-js = true
